# 
policy_path:  "/home/ray/Multi-IMU-Proprioceptive-Odometry/mujoco_go2_him/pre_train/him/go2/policy_1.pt"
xml_path: "go2_him/scene.xml"

# Total simulation time
simulation_duration: 300
# Simulation time step
simulation_dt: 0.005
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 4

kps: [ 20,   20,  20,  20,  20,  20,  20,  20,  20,  20,  20,  20]
kds: [ 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]

default_angles: [ 0.1, 0.8, -1.5, -0.1, 0.8, -1.5, 0.1, 1.0, -1.5, -0.1, 1.0, -1.5]  # for rl model
# default_angles: [ 0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  0.0, 0.0, 0.0]  # for rl model


lin_vel_scale: 2.0
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25 # 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12
num_obs: 270
one_step_obs_size: 45
obs_buffer_size: 6

cmd_init: [0.0, 0.0, 2.5]